name: Go

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: download dependencies
      run: go mod download

    - name: Test
      run: go test -v ./...
    
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v1
    
    - name: login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          muktiarafi/ticketing-common:latest
          muktiarafi/ticketing-common:$GITHUB_SHA
